In [23]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [24]:
# Importation de la base de donnée
import pandas as pd
 #modifprlefun
 
# Importer le dichier excel
df = pd.read_excel("/Users/admin/Documents/GitHub/Data_NA_project/NA.xlsx")  # dict: nom_feuille -> DataFrame
#head
pd.set_option('display.max_columns', None)
df.head()

,Country,Quality Score,SDGi,Life Expectancy,HDI,Per Capita GDP,Region,Income Group,Population (millions),Cropland Footprint,Grazing Footprint,Forest Product Footprint,Fish Footprint,Built up land,Carbon Footprint,Total Ecological Footprint (Production),Cropland Footprint.1,Grazing Footprint.1,Forest Product Footprint.1,Fish Footprint.1,Built up land.1,Carbon Footprint.1,Total Ecological Footprint (Consumption),Cropland,Grazing land,Forest land,Fishing ground,Built up land.2,Total biocapacity,Ecological (Deficit) or Reserve,Number of Earths required,Number of Countries required,actual \nCountry Overshoot Day \n2018
0,Afghanistan,3A,53.9,64.486,0.509,564.617383,Middle East/Central Asia,LI,37.171898,0.139393,0.157740,0.052034,0.000084,0.028433,0.090303,0.467987,0.269788,0.165095,0.062879,0.001060,0.028433,0.155001,0.682255,0.139393,0.157740,0.014377,0.000000,0.028433,0.339943,-0.342312,0.431091,2.006970,NaT
1,Albania,3A,71.0,78.458,0.792,5046.032611,Other Europe,UM,2.882740,0.362065,0.195718,0.163174,0.018087,0.042248,0.639822,1.421114,0.547458,0.195848,0.207561,0.040595,0.042248,0.852748,1.886458,0.362065,0.195718,0.310590,0.082072,0.042248,0.992693,-0.893765,1.191981,1.900343,1900-11-01 05:06:29.557
2,Algeria,3A,70.9,76.693,0.746,4759.830054,Africa,UM,42.228398,0.249653,0.108329,0.079857,0.008417,0.037283,1.200642,1.684182,0.642917,0.150201,0.163528,0.013793,0.037283,1.333187,2.340909,0.249653,0.249356,0.025333,0.007541,0.037283,0.569166,-1.771742,1.479132,4.112872,1900-09-02 18:23:39.042
3,Angola,3A,50.3,60.782,0.582,3233.902767,Africa,LM,30.809801,0.210919,0.054546,0.086584,0.078892,0.046437,0.201850,0.679229,0.329742,0.075853,0.089537,0.091383,0.046437,0.228893,0.861845,0.210919,0.918249,0.486000,0.175160,0.046437,1.836766,0.974922,0.544567,0.469218,NaT
4,Antigua and Barbuda,2B,NaN,76.885,0.772,15134.91009,Central America/Caribbean,HI,0.096286,NaN,NaN,NaN,NaN,NaN,NaN,1.910373,NaN,NaN,NaN,NaN,NaN,NaN,4.655092,NaN,NaN,NaN,NaN,NaN,0.856509,-3.798584,2.941377,5.434962,1900-05-03 02:11:50.646

# Encoder les variables catégorielles avec One hot encoder

https://pbpython.com/categorical-encoding.html

In [25]:
len(df)

184

In [26]:
#df['Region'].value_counts()
df['Quality Score'].value_counts()
#df['Income Group'].value_counts()

Quality Score
3A    140
2A     22
2B     21
2C      1
Name: count, dtype: int64

In [27]:
from sklearn.preprocessing import OneHotEncoder

oe_style = OneHotEncoder()
oe_results_region = oe_style.fit_transform(df[["Region"]])
pd.DataFrame(oe_results_region.toarray(), columns=oe_style.categories_).head()

,Africa,Asia-Pacific,Central America/Caribbean,EU,Middle East/Central Asia,North America,Other Europe,South America
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [28]:
df = df.join(pd.DataFrame(oe_results_region.toarray(), columns=oe_style.categories_))

In [29]:
oe_results_Q_score = oe_style.fit_transform(df[["Quality Score"]])
pd.DataFrame(oe_results_Q_score.toarray(), columns=oe_style.categories_).head()

    2A   2B   2C   3A
0  0.0  0.0  0.0  1.0
1  0.0  0.0  0.0  1.0
2  0.0  0.0  0.0  1.0
3  0.0  0.0  0.0  1.0
4  0.0  1.0  0.0  0.0

In [30]:
df = df.join(pd.DataFrame(oe_results_Q_score.toarray(), columns=oe_style.categories_))

In [31]:
oe_results_I_group = oe_style.fit_transform(df[["Income Group"]])
pd.DataFrame(oe_results_I_group.toarray(), columns=oe_style.categories_).head()

    HI   LI   LM   UM  NaN
0  0.0  1.0  0.0  0.0  0.0
1  0.0  0.0  0.0  1.0  0.0
2  0.0  0.0  0.0  1.0  0.0
3  0.0  0.0  1.0  0.0  0.0
4  1.0  0.0  0.0  0.0  0.0

In [32]:
print("Nombre de lignes dans df :", len(df))
print("Nombre de lignes dans oe_results_I_group.toarray() :", oe_results_I_group.toarray().shape[0])
print("Nombre de catégories dans oe_style.categories_ :", len(oe_style.categories_))
print("Nombre de colonnes dans oe_results_I_group.toarray() :", oe_results_I_group.toarray().shape[1])

Nombre de lignes dans df : 184
Nombre de lignes dans oe_results_I_group.toarray() : 184
Nombre de catégories dans oe_style.categories_ : 1
Nombre de colonnes dans oe_results_I_group.toarray() : 5

In [33]:
#df = df.join(pd.DataFrame(oe_results_I_group.toarray(), columns=oe_style.categories_))
# Mettez à jour oe_style.categories_ pour qu'il ait 5 catégories
oe_style.categories_ = ['HI', 'LI', 'LM', 'UM', 'NaN']  # Remplacez par vos catégories réelles
df_oe_results = pd.DataFrame(oe_results_I_group.toarray(), columns=oe_style.categories_, index=df.index)

# Effectuez la jointure
df = df.join(df_oe_results)

In [ ]:
df.head()

,Country,Quality Score,SDGi,Life Expectancy,HDI,Per Capita GDP,Region,Income Group,Population (millions),Cropland Footprint,Grazing Footprint,Forest Product Footprint,Fish Footprint,Built up land,Carbon Footprint,Total Ecological Footprint (Production),Cropland Footprint.1,Grazing Footprint.1,Forest Product Footprint.1,Fish Footprint.1,Built up land.1,Carbon Footprint.1,Total Ecological Footprint (Consumption),Cropland,Grazing land,Forest land,Fishing ground,Built up land.2,Total biocapacity,Ecological (Deficit) or Reserve,Number of Earths required,Number of Countries required,actual \nCountry Overshoot Day \n2018,"(Africa,)","(Asia-Pacific,)","(Central America/Caribbean,)","(EU,)","(Middle East/Central Asia,)","(North America,)","(Other Europe,)","(South America,)","(2A,)","(2B,)","(2C,)","(3A,)",HI,LI,LM,UM,NaN
0,Afghanistan,3A,53.9,64.486,0.509,564.617383,Middle East/Central Asia,LI,37.171898,0.139393,0.157740,0.052034,0.000084,0.028433,0.090303,0.467987,0.269788,0.165095,0.062879,0.001060,0.028433,0.155001,0.682255,0.139393,0.157740,0.014377,0.000000,0.028433,0.339943,-0.342312,0.431091,2.006970,NaT,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
1,Albania,3A,71.0,78.458,0.792,5046.032611,Other Europe,UM,2.882740,0.362065,0.195718,0.163174,0.018087,0.042248,0.639822,1.421114,0.547458,0.195848,0.207561,0.040595,0.042248,0.852748,1.886458,0.362065,0.195718,0.310590,0.082072,0.042248,0.992693,-0.893765,1.191981,1.900343,1900-11-01 05:06:29.557,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,Algeria,3A,70.9,76.693,0.746,4759.830054,Africa,UM,42.228398,0.249653,0.108329,0.079857,0.008417,0.037283,1.200642,1.684182,0.642917,0.150201,0.163528,0.013793,0.037283,1.333187,2.340909,0.249653,0.249356,0.025333,0.007541,0.037283,0.569166,-1.771742,1.479132,4.112872,1900-09-02 18:23:39.042,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,Angola,3A,50.3,60.782,0.582,3233.902767,Africa,LM,30.809801,0.210919,0.054546,0.086584,0.078892,0.046437,0.201850,0.679229,0.329742,0.075853,0.089537,0.091383,0.046437,0.228893,0.861845,0.210919,0.918249,0.486000,0.175160,0.046437,1.836766,0.974922,0.544567,0.469218,NaT,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,Antigua and Barbuda,2B,NaN,76.885,0.772,15134.91009,Central America/Caribbean,HI,0.096286,NaN,NaN,NaN,NaN,NaN,NaN,1.910373,NaN,NaN,NaN,NaN,NaN,NaN,4.655092,NaN,NaN,NaN,NaN,NaN,0.856509,-3.798584,2.941377,5.434962,1900-05-03 02:11:50.646,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [ ]:
len(df)

184