In [35]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [36]:
# Importation de la base de donnée
import pandas as pd
 #modifprlefun
 
# Importer le dichier excel
excel_file = "/Users/matteoschweizer/Desktop/M1_SSD/projetNa/Base de données projet.xlsx"

# Lire la feuille Excel
df = pd.read_excel(excel_file)

# Chemin du fichier CSV de sortie
csv_file = "/Users/matteoschweizer/Desktop/M1_SSD/projetNa/project_bd.csv"

# Exporter en CSV
df.to_csv(csv_file, index=False)

# Lire le CSV
data = pd.read_csv(csv_file)

In [37]:
data.head()

,Country,Quality Score,SDGi,Life Expectancy,HDI,Per Capita GDP,Region,Income Group,Population (millions),Cropland Footprint,Grazing Footprint,Forest Product Footprint,Fish Footprint,Built up land,Carbon Footprint,Total Ecological Footprint (Production),Cropland Footprint.1,Grazing Footprint.1,Forest Product Footprint.1,Fish Footprint.1,Built up land.1,Carbon Footprint.1,Total Ecological Footprint (Consumption),Cropland,Grazing land,Forest land,Fishing ground,Built up land.2,Total biocapacity,Ecological (Deficit) or Reserve,Number of Earths required,Number of Countries required,actual \nCountry Overshoot Day \n2018
0,Afghanistan,3A,53.9,64.486,0.509,564.6173825447371,Middle East/Central Asia,LI,37.171898,0.139393,0.157740,0.052034,0.000084,0.028433,0.090303,0.467987,0.269788,0.165095,0.062879,0.001060,0.028433,0.155001,0.682255,0.139393,0.157740,0.014377,0.000000,0.028433,0.339943,-0.342312,0.431091,2.006970,NaN
1,Albania,3A,71.0,78.458,0.792,5046.032611084467,Other Europe,UM,2.882740,0.362065,0.195718,0.163174,0.018087,0.042248,0.639822,1.421114,0.547458,0.195848,0.207561,0.040595,0.042248,0.852748,1.886458,0.362065,0.195718,0.310590,0.082072,0.042248,0.992693,-0.893765,1.191981,1.900343,1900-11-01 05:06:29.557
2,Algeria,3A,70.9,76.693,0.746,4759.830053642441,Africa,UM,42.228398,0.249653,0.108329,0.079857,0.008417,0.037283,1.200642,1.684182,0.642917,0.150201,0.163528,0.013793,0.037283,1.333187,2.340909,0.249653,0.249356,0.025333,0.007541,0.037283,0.569166,-1.771742,1.479132,4.112872,1900-09-02 18:23:39.042
3,Angola,3A,50.3,60.782,0.582,3233.902767090789,Africa,LM,30.809801,0.210919,0.054546,0.086584,0.078892,0.046437,0.201850,0.679229,0.329742,0.075853,0.089537,0.091383,0.046437,0.228893,0.861845,0.210919,0.918249,0.486000,0.175160,0.046437,1.836766,0.974922,0.544567,0.469218,NaN
4,Antigua and Barbuda,2B,NaN,76.885,0.772,15134.910089609682,Central America/Caribbean,HI,0.096286,NaN,NaN,NaN,NaN,NaN,NaN,1.910373,NaN,NaN,NaN,NaN,NaN,NaN,4.655092,NaN,NaN,NaN,NaN,NaN,0.856509,-3.798584,2.941377,5.434962,1900-05-03 02:11:50.646

In [38]:
len(data.columns)
len(data)

184

In [39]:
Y_col = "actual \nCountry Overshoot Day \n2018"
X_cols = [col for col in data.columns if col != Y_col]
all = X_cols + [Y_col]
df_clean = data.replace("-", np.nan)
df_supervised = data.dropna(subset=X_cols + [Y_col])

df_semi_Xcomplete_Ymissing = data.dropna(subset=X_cols)# X complets
df_semi_Ycomplete_Xmissing = data.dropna(subset=[Y_col])# Y complet
df_NA = data.copy()

df_NA=df_NA[df_NA[Y_col].isna() | df_NA[X_cols].isna().any(axis=1)]

In [40]:
len(df_NA)
#print(df_NA["Country"].to_list())

75

Récupération des datasets pour tout les scénarios

In [41]:
df_supervised.to_csv("supervised.csv", index=False)
df_semi_Xcomplete_Ymissing.to_csv("semi_Xcomplete_Ymissing.csv", index=False)
df_semi_Ycomplete_Xmissing.to_csv("semi_Ycomplete_Xmissing.csv", index=False)
#df_unsupervised.to_csv("non_supervised.csv", index=False)

Ici le jeux de donnée pour le modele 2 c'est df_semi_Xcomplete_Ymissing.

In [42]:
df_semi_Xcomplete_Ymissing.head(2)
len(df_semi_Xcomplete_Ymissing)

148

In [43]:
df=df_semi_Xcomplete_Ymissing

In [44]:
df["actual \nCountry Overshoot Day \n2018"]=pd.to_datetime(df["actual \nCountry Overshoot Day \n2018"])
df["actual \nCountry Overshoot Day \n2018"]=df["actual \nCountry Overshoot Day \n2018"].dt.day_of_year
df.head()
#df.dtypes

/var/folders/7c/7n2rtly56rj_gvfcqvdfq9sm0000gn/T/ipykernel_30208/2434865298.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["actual \nCountry Overshoot Day \n2018"]=pd.to_datetime(df["actual \nCountry Overshoot Day \n2018"])
/var/folders/7c/7n2rtly56rj_gvfcqvdfq9sm0000gn/T/ipykernel_30208/2434865298.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["actual \nCountry Overshoot Day \n2018"]=df["actual \nCountry Overshoot Day \n2018"].dt.day_of_year

,Country,Quality Score,SDGi,Life Expectancy,HDI,Per Capita GDP,Region,Income Group,Population (millions),Cropland Footprint,Grazing Footprint,Forest Product Footprint,Fish Footprint,Built up land,Carbon Footprint,Total Ecological Footprint (Production),Cropland Footprint.1,Grazing Footprint.1,Forest Product Footprint.1,Fish Footprint.1,Built up land.1,Carbon Footprint.1,Total Ecological Footprint (Consumption),Cropland,Grazing land,Forest land,Fishing ground,Built up land.2,Total biocapacity,Ecological (Deficit) or Reserve,Number of Earths required,Number of Countries required,actual \nCountry Overshoot Day \n2018
0,Afghanistan,3A,53.9,64.486,0.509,564.6173825447371,Middle East/Central Asia,LI,37.171898,0.139393,0.157740,0.052034,0.000084,0.028433,0.090303,0.467987,0.269788,0.165095,0.062879,0.001060,0.028433,0.155001,0.682255,0.139393,0.157740,0.014377,0.000000,0.028433,0.339943,-0.342312,0.431091,2.006970,NaN
1,Albania,3A,71.0,78.458,0.792,5046.032611084467,Other Europe,UM,2.882740,0.362065,0.195718,0.163174,0.018087,0.042248,0.639822,1.421114,0.547458,0.195848,0.207561,0.040595,0.042248,0.852748,1.886458,0.362065,0.195718,0.310590,0.082072,0.042248,0.992693,-0.893765,1.191981,1.900343,305.0
2,Algeria,3A,70.9,76.693,0.746,4759.830053642441,Africa,UM,42.228398,0.249653,0.108329,0.079857,0.008417,0.037283,1.200642,1.684182,0.642917,0.150201,0.163528,0.013793,0.037283,1.333187,2.340909,0.249653,0.249356,0.025333,0.007541,0.037283,0.569166,-1.771742,1.479132,4.112872,245.0
3,Angola,3A,50.3,60.782,0.582,3233.902767090789,Africa,LM,30.809801,0.210919,0.054546,0.086584,0.078892,0.046437,0.201850,0.679229,0.329742,0.075853,0.089537,0.091383,0.046437,0.228893,0.861845,0.210919,0.918249,0.486000,0.175160,0.046437,1.836766,0.974922,0.544567,0.469218,NaN
5,Argentina,3A,72.8,76.520,0.842,10076.39540623727,South America,UM,44.361102,2.207423,0.969692,0.250688,0.174034,0.092705,1.381537,5.076080,0.908614,0.717147,0.276678,0.083593,0.092705,1.233009,3.311746,2.207423,1.721421,0.609912,1.548194,0.092705,6.179656,2.867910,2.092567,0.535911,173.0

In [45]:
pd.set_option('display.max_columns', None)
df.head()
#df.columns

,Country,Quality Score,SDGi,Life Expectancy,HDI,Per Capita GDP,Region,Income Group,Population (millions),Cropland Footprint,Grazing Footprint,Forest Product Footprint,Fish Footprint,Built up land,Carbon Footprint,Total Ecological Footprint (Production),Cropland Footprint.1,Grazing Footprint.1,Forest Product Footprint.1,Fish Footprint.1,Built up land.1,Carbon Footprint.1,Total Ecological Footprint (Consumption),Cropland,Grazing land,Forest land,Fishing ground,Built up land.2,Total biocapacity,Ecological (Deficit) or Reserve,Number of Earths required,Number of Countries required,actual \nCountry Overshoot Day \n2018
0,Afghanistan,3A,53.9,64.486,0.509,564.6173825447371,Middle East/Central Asia,LI,37.171898,0.139393,0.157740,0.052034,0.000084,0.028433,0.090303,0.467987,0.269788,0.165095,0.062879,0.001060,0.028433,0.155001,0.682255,0.139393,0.157740,0.014377,0.000000,0.028433,0.339943,-0.342312,0.431091,2.006970,NaN
1,Albania,3A,71.0,78.458,0.792,5046.032611084467,Other Europe,UM,2.882740,0.362065,0.195718,0.163174,0.018087,0.042248,0.639822,1.421114,0.547458,0.195848,0.207561,0.040595,0.042248,0.852748,1.886458,0.362065,0.195718,0.310590,0.082072,0.042248,0.992693,-0.893765,1.191981,1.900343,305.0
2,Algeria,3A,70.9,76.693,0.746,4759.830053642441,Africa,UM,42.228398,0.249653,0.108329,0.079857,0.008417,0.037283,1.200642,1.684182,0.642917,0.150201,0.163528,0.013793,0.037283,1.333187,2.340909,0.249653,0.249356,0.025333,0.007541,0.037283,0.569166,-1.771742,1.479132,4.112872,245.0
3,Angola,3A,50.3,60.782,0.582,3233.902767090789,Africa,LM,30.809801,0.210919,0.054546,0.086584,0.078892,0.046437,0.201850,0.679229,0.329742,0.075853,0.089537,0.091383,0.046437,0.228893,0.861845,0.210919,0.918249,0.486000,0.175160,0.046437,1.836766,0.974922,0.544567,0.469218,NaN
5,Argentina,3A,72.8,76.520,0.842,10076.39540623727,South America,UM,44.361102,2.207423,0.969692,0.250688,0.174034,0.092705,1.381537,5.076080,0.908614,0.717147,0.276678,0.083593,0.092705,1.233009,3.311746,2.207423,1.721421,0.609912,1.548194,0.092705,6.179656,2.867910,2.092567,0.535911,173.0

# Encoder les variables catégorielles avec One hot encoder

https://pbpython.com/categorical-encoding.html

In [57]:
df_numerique=df[["Quality Score", "Region", "Income Group",'SDGi', 'Country', 'Life Expectancy', 'HDI',
                           'Per Capita GDP', 'Population (millions)',
                           'Cropland Footprint', 'Grazing Footprint', 'Forest Product Footprint',
                           'Fish Footprint', 'Built up land', 'Carbon Footprint',
                           'Total Ecological Footprint (Production)', 'Cropland Footprint.1',
                           'Grazing Footprint.1', 'Forest Product Footprint.1', 'Fish Footprint.1',
                           'Built up land.1', 'Carbon Footprint.1',
                           'Total Ecological Footprint (Consumption)', 'Cropland', 'Grazing land',
                           'Forest land', 'Fishing ground', 'Built up land.2',
                           'Total biocapacity ', 'Ecological (Deficit) or Reserve',
                           'Number of Earths required', 'Number of Countries required',
                           'actual \nCountry Overshoot Day \n2018']]

In [58]:
#mettre counrty comme index
df_numerique = df_numerique.set_index('Country')
df_numerique.head()
len(df_numerique)

148

In [72]:
#df['Region'].value_counts()
df['Quality Score'].value_counts()
#df['Income Group'].value_counts()

Quality Score
3A    130
2A     18
Name: count, dtype: int64

In [60]:
len(df)

148

In [61]:
#création du tableau avec les var quali
df_quali=df[["Quality Score", "Region", "Income Group"]]

In [67]:
from sklearn.preprocessing import OneHotEncoder

oe_style = OneHotEncoder()
oe_results_region = oe_style.fit_transform(df_numerique[["Region"]])
pd.DataFrame(oe_results_region.toarray(), columns=oe_style.categories_).head()

,Africa,Asia-Pacific,Central America/Caribbean,EU,Middle East/Central Asia,North America,Other Europe,South America
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [65]:
oe_results_Q_score = oe_style.fit_transform(df_numerique[["Quality Score"]])
pd.DataFrame(oe_results_Q_score.toarray(), columns=oe_style.categories_).head()

    2A   3A
0  0.0  1.0
1  0.0  1.0
2  0.0  1.0
3  0.0  1.0
4  0.0  1.0

In [66]:
oe_results_I_group = oe_style.fit_transform(df_numerique[["Income Group"]])
pd.DataFrame(oe_results_I_group.toarray(), columns=oe_style.categories_).head()

    HI   LI   LM   UM
0  0.0  1.0  0.0  0.0
1  0.0  0.0  0.0  1.0
2  0.0  0.0  0.0  1.0
3  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  1.0

In [70]:
df = df.join(pd.DataFrame(oe_results_region.toarray(), columns=oe_style.categories_))

In [68]:
df_numerique = df_numerique.join(pd.DataFrame(oe_results_region.toarray(), columns=oe_style.categories_))
df_numerique = df_numerique.join(pd.DataFrame(oe_results_Q_score.toarray(), columns=oe_style.categories_))
df_numerique = df_numerique.join(pd.DataFrame(oe_results_I_group.toarray(), columns=oe_style.categories_))

ValueError: Shape of passed values is (148, 2), indices imply (148, 8)

In [71]:
df.head()

,Country,Quality Score,SDGi,Life Expectancy,HDI,Per Capita GDP,Region,Income Group,Population (millions),Cropland Footprint,Grazing Footprint,Forest Product Footprint,Fish Footprint,Built up land,Carbon Footprint,Total Ecological Footprint (Production),Cropland Footprint.1,Grazing Footprint.1,Forest Product Footprint.1,Fish Footprint.1,Built up land.1,Carbon Footprint.1,Total Ecological Footprint (Consumption),Cropland,Grazing land,Forest land,Fishing ground,Built up land.2,Total biocapacity,Ecological (Deficit) or Reserve,Number of Earths required,Number of Countries required,actual \nCountry Overshoot Day \n2018,"(Africa,)","(Asia-Pacific,)","(Central America/Caribbean,)","(EU,)","(Middle East/Central Asia,)","(North America,)","(Other Europe,)","(South America,)"
0,Afghanistan,3A,53.9,64.486,0.509,564.6173825447371,Middle East/Central Asia,LI,37.171898,0.139393,0.157740,0.052034,0.000084,0.028433,0.090303,0.467987,0.269788,0.165095,0.062879,0.001060,0.028433,0.155001,0.682255,0.139393,0.157740,0.014377,0.000000,0.028433,0.339943,-0.342312,0.431091,2.006970,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,Albania,3A,71.0,78.458,0.792,5046.032611084467,Other Europe,UM,2.882740,0.362065,0.195718,0.163174,0.018087,0.042248,0.639822,1.421114,0.547458,0.195848,0.207561,0.040595,0.042248,0.852748,1.886458,0.362065,0.195718,0.310590,0.082072,0.042248,0.992693,-0.893765,1.191981,1.900343,305.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,Algeria,3A,70.9,76.693,0.746,4759.830053642441,Africa,UM,42.228398,0.249653,0.108329,0.079857,0.008417,0.037283,1.200642,1.684182,0.642917,0.150201,0.163528,0.013793,0.037283,1.333187,2.340909,0.249653,0.249356,0.025333,0.007541,0.037283,0.569166,-1.771742,1.479132,4.112872,245.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Angola,3A,50.3,60.782,0.582,3233.902767090789,Africa,LM,30.809801,0.210919,0.054546,0.086584,0.078892,0.046437,0.201850,0.679229,0.329742,0.075853,0.089537,0.091383,0.046437,0.228893,0.861845,0.210919,0.918249,0.486000,0.175160,0.046437,1.836766,0.974922,0.544567,0.469218,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Argentina,3A,72.8,76.520,0.842,10076.39540623727,South America,UM,44.361102,2.207423,0.969692,0.250688,0.174034,0.092705,1.381537,5.076080,0.908614,0.717147,0.276678,0.083593,0.092705,1.233009,3.311746,2.207423,1.721421,0.609912,1.548194,0.092705,6.179656,2.867910,2.092567,0.535911,173.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0